services:
  website:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./posts:/app/posts
      - ./static:/app/static
    environment:
      - FLASK_DEBUG=1
    restart: unless-stopped
